### ISSUE TITLE
2-nd version release checklist

### ISSUE THREAD

**Issue by fckt** [paritytech/parity-signer#112]
- [x] account database migration on the first run (some additional fields was added)
- [x] About Accounts button does not work https://github.com/paritytech/parity-signer/issues/124
- [x] Rename App from NativeSigner to Parity Signer (Android)
- [x] Resolve this https://github.com/paritytech/parity-signer/issues/122, decide if we need https://github.com/paritytech/parity-signer/issues/121
