### ISSUE TITLE
Dynamic derivations

### ISSUE THREAD

**Issue by prybalko** [paritytech/parity-signer#1881]
Polkadot Vault has to be used for getting Dynamically derived account address for further operating dynamically derived account in the Nova Spektr application. Dynamic derivation may be created outside the Polkadot Vault.

More details:
https://gist.github.com/pgolovkin/0a45a5ea860fbfe7d0e7fd883c40c783

Design:
https://www.figma.com/file/k0F8XYk9XVYdKLtkj0Vzp5/Signer-(Vault)-%C2%B7-Redesign?type=design&node-id=13663-65511

## Test data
Test seed phrase: `bottom drive obey lake curtain smoke basket hold race lonely fit walk`
#### Import dynamic derivations
This QR contains two derivations: `//dd` for polkadot and `//nonetwork` for unknown network

![test](https://github.com/paritytech/parity-signer/assets/7165377/d9920d3d-8ae7-456c-8ed4-be0ae060d7d1)

```[tasklist]
### Tasks
- [X] Design
- [ ] https://github.com/paritytech/parity-signer/issues/1882
- [ ] https://github.com/paritytech/parity-signer/issues/1883
- [ ] https://github.com/paritytech/parity-signer/issues/1884
- [ ] https://github.com/paritytech/parity-signer/issues/1885
- [ ] https://github.com/paritytech/parity-signer/issues/1997
```

**Comment by Dmitry-Borodin** [comment]
@prybalko looks like it's done, right?

**Comment by prybalko** [comment]
> @prybalko looks like it's done, right?

There is one more. There should be a `jdenticon` displayed on the key set menu

**Comment by Dmitry-Borodin** [comment]
@prybalko I think now this issue is done, should we close it?

**Comment by prybalko** [comment]
> @prybalko I think now this issue is done, should we close it?

Yes, thank you for the reminder.
