### ISSUE TITLE
Final Substrate support tracking issue

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-signer#240]
**Parity Signer**
+ [x] Account refactoring @hanwencheng #252
+ [x] QR code reading support for UOS @yjkimjunior #253
+ [x] Substrate account generation and QR code display @Tbaut https://github.com/paritytech/parity-signer/pull/301 and https://github.com/paritytech/parity-signer/pull/293

**External JS tools**
+ [x] ~~[QR-Signer](https://github.com/parity-js/qr-signer) needs to be updated to support UOS (read and generate QR codes). @amaurymartiny in https://github.com/parity-js/qr-signer/pull/75~~ not needed
- [ ] Create an app to generate and display the QR code from Txs, scan signed Txs and send them to the blockchain. @jacogr https://github.com/polkadot-js/apps/issues/355 

**Rust**
+ [x] Expose needed functions for Substrate support https://github.com/paritytech/parity-signer/issues/155 @maciejhirsz

**Comment by Tbaut** [comment]
Closing as most of it is done in this repo. The next item is the compatibility in apps.
