### ISSUE TITLE
[meta] Add Metadata and Network management

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-signer#408]
List of 
- [x] Network management page: https://github.com/paritytech/parity-signer/issues/406
- [x] Metadata management page: https://github.com/paritytech/parity-signer/issues/407
- [x] Add network with QR scan: https://github.com/paritytech/parity-signer/issues/302
- [x] Inject types for metadata: https://github.com/paritytech/parity-signer/issues/318
- [x] Setup website page with signed QR codes

**Comment by Slesarew** [comment]
I'm just marking this as last remaining step before metadata updates become real thing - we need to figure out how to build, sign and post them somewhere (including companions).

**Comment by Slesarew** [comment]
Finally, metadata portal is [up](https://metadata.parity.io/)
