### ISSUE TITLE
Roadmap track of v4 version

### ISSUE THREAD

**Issue by hanwencheng** [paritytech/parity-signer#535]
This issue tracks the milestones for the major release of v4 version

v4.0
- [x] HDKD feature #431
- [x] Enable create custom path with a selected network #533

v4.1
- [x] migrate to typescript #521 
- [x] update React Native to latest version
- [x] integrate password with seed generation #565 

v4.2
- [x] Use pointer to get seed from protected rust runtime. #489 Details see this [gist](https://github.com/hanwencheng/gists/blob/master/KeyPointer/KeyPointer.md)

v4.3
- [x] PolkadotCC1 network support #629 

v4.4 
- [x] support export derived account #640
- [x] refactor the navigation bar to the bottom. #643 

v4.5
- [x] metadata and network management, ~offline meta data update~ #668  #681 

### Future Improvement

- [x] Inject Metadata update QR #318
- [ ] import an derived account #588 
- [x] Ed25519 and Ecdsa support #614 
- [x] message signing

*NOTICE: Since there are extra test and backward-compatibility work, v4 will first focus on the functionality for the current identity structure rather than the legacy account from v3. in next major release v5 we will not support legacy accounts.*
