### ISSUE TITLE
UI: suggestions umbrella

### ISSUE THREAD

**Issue by goldsteinsveta** [paritytech/parity-signer#961]
- [ ] Users do not see drawer menus. Content of the screens should be faded out (with Bg600 alpha 50%) when a drawer menu is visible.
_See [video](https://drive.google.com/file/d/1gyZBbW-21PgUbYvbPPu-S9SMA_O84PSt/view?usp=sharing)_
There could be a contrast "handle" on the top of the drawer menu if it's not enough
- [ ] Quick access to `N+1` and `Delete` derived key is undiscoverable. There should be a continuous movement of the whole card or its parts while dragging.
_See [video](https://drive.google.com/file/d/18IeqsgQlgT29ktr9QA6ynA8k_cjA-biB/view?usp=sharing) and [design doc](https://www.figma.com/file/jkVxsKUahgJpGOxrrfOI9H/?node-id=1624%3A15791)_
- [ ] Export screen should be different from Key screen. Users don't get how the Export screen works.
_See [video](https://drive.google.com/file/d/1u3bdwPTjp7brZDmWwhpltDT9onU-GZKl/view?usp=sharing) and [design doc](https://www.figma.com/file/jkVxsKUahgJpGOxrrfOI9H/?node-id=1628%3A16229)_
- [ ] Bulk select checkmarks are hard to see on the top of an identicon. More common pattern is to move selectable items to the right to give space for the checkmark icon to the left of the selectable item.
_See [video](https://drive.google.com/file/d/1u3bdwPTjp7brZDmWwhpltDT9onU-GZKl/view?usp=sharing) and [design doc](https://www.figma.com/file/jkVxsKUahgJpGOxrrfOI9H/?node-id=1628%3A16229) (same as previous)_

**Comment by goldsteinsveta** [comment]
added videos and design docs to respective tasks
